// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM2jufBnIIXVul2YBc0K0N0pAPpRBPSsI',
    appId: '1:1005682887137:web:5202d502a99ea5faf72aa0',
    messagingSenderId: '1005682887137',
    projectId: 'section-b-jawan-pakistan',
    authDomain: 'section-b-jawan-pakistan.firebaseapp.com',
    storageBucket: 'section-b-jawan-pakistan.appspot.com',
    measurementId: 'G-TG5M9E9382',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCTleiXT4lQinoJtqKXB6n0SfCvrHGURQ',
    appId: '1:1005682887137:android:1f45123372757ac7f72aa0',
    messagingSenderId: '1005682887137',
    projectId: 'section-b-jawan-pakistan',
    storageBucket: 'section-b-jawan-pakistan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ADSPsNXU5izLsc7YxtbyCU3jPbYB9Xs',
    appId: '1:1005682887137:ios:c7039342b2118fcbf72aa0',
    messagingSenderId: '1005682887137',
    projectId: 'section-b-jawan-pakistan',
    storageBucket: 'section-b-jawan-pakistan.appspot.com',
    iosClientId: '1005682887137-plgi7nj6442n357njb33h6lu2ml6rg8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseclass',
  );
}
